domino__action_switch: {
  install: install,
  uninstall: uninstall,
  start: start,
  stop: stop
}

domino__supported_os:
  - redhat

domino__enable_fw_services:
  - https
  - http
  - lotusnote
  - ldap
  - imap

domino__all_products:
  - domino
  - verse
  - nomad
  - traveler
  - leap
  - domrestapi

domino__software_repo: https://raw.githubusercontent.com/HCL-TECH-SOFTWARE/domino-container
domino__software_repo_branch: develop      # options: main, develop
domino__software_file_url: '{{ domino__software_repo }}/{{ domino__software_repo_branch }}/software/software.txt'
domino__software_latest_file_url: '{{ domino__software_repo }}/{{ domino__software_repo_branch }}/software/current_version.txt'
domino__software_directory: '{{ role_path }}/software'
domino__software_file: software.txt
domino__software_latest_file: current_version.txt

domino__users_file: users.csv

domino__directories:
  - /local/notesdata
  - /local/translog
  - /local/daos
  - /local/nif
  - /local/ft
  - /local/backup
  - /local/backup/nsf
  - /local/backup/translog
  - /local/backup/log

domino__installer_subdirectory: installers
domino__installers_dir: '{{ domino__install_path }}/{{ domino__installer_subdirectory }}'

domino__domino_install_subdir: domino
domino__domino_install: '{{ domino__install_path }}/{{ domino__domino_install_subdir }}'

domino__fixpack_install_subdir: fp
domino__fixpack_install: '{{ domino__install_path }}/{{ domino__fixpack_install_subdir }}'

domino__if_install_subdir: if
domino__if_install: '{{ domino__install_path }}/{{ domino__if_install_subdir }}'

domino__traveler_install_subdir: traveler
domino__traveler_install: '{{ domino__install_path }}/{{ domino__traveler_install_subdir }}'

domino__verse_install_subdir: verse
domino__verse_install: '{{ domino__install_path }}/{{ domino__verse_install_subdir }}'

domino__nomad_install_subdir: nomad
domino__nomad_install: '{{ domino__install_path }}/{{ domino__nomad_install_subdir }}'

domino__leap_install_subdir: leap
domino__leap_install: '{{ domino__install_path }}/{{ domino__leap_install_subdir }}'

domino__domrestapi_install_subdir: domrestapi
domino__domrestapi_install: '{{ domino__install_path }}/{{ domino__domrestapi_install_subdir }}'

domino__response_file: '{{ domino__install_path }}/installer.properties'

domino__nek: credstorekey
domino__credstore: credstore
domino__default_login_db: domcfg.nsf
domino__default_login_form: $$LoginUserForm

domino__dkim_info: dkim-info.txt

domino__verify_tasks:
  - { name: service, description: 'Domino service registered in the OS' }
  - { name: port_nrpc, description: 'NRPC port 1352 is listening' }
  - { name: port_ldap, description: 'LDAP port 389 is listening' }
  - { name: notesini, description: 'Custom notes.ini parameters validated' }
  - { name: users, description: 'Initial users created' }
