---
- name: Check that server has correct Linux kernel for Domino V14
  vars:
    domino_version: '{{ product_info | json_query("[?name==`domino`].version") | first  }}'
  ansible.builtin.assert:
    that:
      - ansible_kernel is version('5.14', '>=')
    fail_msg: 'The Linux kernel version on server must be higher than 5.14: {{ ansible_kernel }}'
    success_msg: 'The Linux kernel version on server is equal or higher than 5.14: {{ ansible_kernel }}'
  when: domino_version is version('14.0', '>=')
