---

# ---------- CHECK WHETHER NOMAD IS ALREADY INSTALLED

- name: Check if Domino log file file exists
  ansible.builtin.stat:
    path: /local/notesdata/log.nsf
  register: nomad_installed_result

- name: Mark Nomad as installed (single variable)
  ansible.builtin.set_fact:
    nomad_is_installed: true
  when:
    - nomad_installed_result.stat.exists

- name: Mark Nomad as installed (sw dictionary)
  vars:
    index: '{{ product_info | ansible.utils.index_of("eq", "nomad", "name") }}'
  ansible.utils.update_fact:
    updates:
      - path: 'product_info.{{ index }}.installed'
        value: true
  when:
    - nomad_installed_result.stat.exists
    - domino__install_nomad
  changed_when: false
  register: product_info_updated_result

- name: Store the updated value into the master fact
  ansible.builtin.set_fact:
    product_info: '{{ product_info_updated_result.product_info }}'
  when:
    - nomad_installed_result.stat.exists
    - domino__install_nomad
