---
- name: Calculate Verse binaries path (based on the Domino server version)
  vars:
    verse_v14_path: '/local/notesdata/domino/workspace/applications/eclipse/plugins'
    verse_v14_5_path: '/opt/hcl/domino/notes/latest/linux/osgi/shared/eclipse/plugins'
  ansible.builtin.set_fact:
    verse_path: '{{ (domino_main_version == "14.5") | ternary(verse_v14_5_path, verse_v14_path) }}'

- name: Check that at least one Verse binary file exists
  ansible.builtin.find:
    paths: '{{ verse_path }}'
    patterns: 'core-*.jar'
    file_type: file
    recurse: false
  register: verse_find_result

- name: Perform tasks when Verse server is already installed
  when: verse_find_result.matched > 0
  block:
    - name: Get version from the Verse binary filename
      vars:
        # Sort the list of all core-*.jar files and take the last one (with the highest version)
        verse_filename: '{{ verse_find_result.files | json_query("[*].path") | sort | last | basename }}'
      ansible.builtin.set_fact:
        # Get the version substring from the filename
        verse_version: '{{ verse_filename.split("-")[1] }}'

    - name: Mark Verse as installed (single variable)
      ansible.builtin.set_fact:
        verse_is_installed: true

    - name: Mark Verse as installed (sw dictionary)
      vars:
        index: '{{ product_info | ansible.utils.index_of("eq", "verse", "name") }}'
        verse_target_version: '{{ product_info | json_query("[?name==`verse`].version") | first  }}'
        target_version_is_newer: '{{ verse_version is version(verse_target_version, "<", version_type="loose") }}'
      ansible.utils.update_fact:
        updates:
          - path: 'product_info.{{ index }}.installed'
            value: true
          - path: 'product_info.{{ index }}.installed_version'
            value: '{{ verse_version }}'
          - path: 'product_info.{{ index }}.do_installation'
            value: '{{ target_version_is_newer }}'
      changed_when: false
      register: product_info_updated_result

    - name: Store the updated value into the master fact
      ansible.builtin.set_fact:
        product_info: '{{ product_info_updated_result.product_info }}'
