---
all:
  children:

    example:
      children:
        domino:
          hosts:
            alpha.example.com:
              ansible_host: alpha.example.com
              ansible_user: ansible
              ansible_ssh_private_key_file: /repo/local/keys/id_rsa
            beta.example.com:
              ansible_host: beta.example.com
              ansible_user: ansible
              ansible_ssh_private_key_file: /repo/local/keys/id_rsa
