domino__server_name: Beta
domino__domino_hostname: beta.example.com
domino__domino_domain: Example
domino__org_name: Example
domino__create_microca: true
domino__certifier_password: password
domino__admin_password: password
domino__register_users: true
domino__input_data_location: '{{ playbook_dir }}/../local'
domino__install_as_additional: true
domino__existing_server_name: Alpha
domino__existing_server_address: alpha.example.com
domino__wait_mins_after_restart: 0
