namespace: hclsoftware
name: domino
version: 1.0.0
readme: README.md
authors:
  - Thomas Hampel <thomas.hampel@pnp-hcl.com>
  - Petr Kunc <petr.kunc@hcl-software.com>
description: Deploys HCL Domino server on a Linux machine
license:
  - Apache-2.0
tags: [linux, application, hclsoftware, domino]
dependencies: {}
repository: https://github.com/HCL-TECH-SOFTWARE/Domino-Automation
