---
galaxy_info:
  role_name: semaphore
  description: Performs initial Semaphore configuration
  author: Petr Kunc
  company: HCLSoftware
  license: Apache License 2.0
  min_ansible_version: '2.11'

dependencies: []
