---
- name: Check Domino service in OS
  ansible.builtin.import_tasks:
    file: verify/service.yml

- name: Check ports for Domino services
  ansible.builtin.import_tasks:
    file: verify/ports.yml

- name: Check registered users
  ansible.builtin.import_tasks:
    file: verify/users.yml
  when:
    - domino__register_users

- name: Check Domino notes.ini parameters
  ansible.builtin.import_tasks:
    file: verify/notesini.yml

- name: Check Domino TLS certificates
  ansible.builtin.import_tasks:
    file: verify/certificates.yml

- name: Check Traveler
  ansible.builtin.import_tasks:
    file: verify/traveler.yml
  when:
    - domino__install_traveler

- name: Check Verse
  ansible.builtin.import_tasks:
    file: verify/verse.yml
  when:
    - domino__install_verse

- name: Check Leap
  ansible.builtin.import_tasks:
    file: verify/leap.yml
  when:
    - domino__install_leap

- name: Check Nomad
  ansible.builtin.import_tasks:
    file: verify/nomad.yml
  when:
    - domino__install_nomad

- name: Check DRAPI
  ansible.builtin.import_tasks:
    file: verify/drapi.yml
  when:
    - domino__install_domrestapi

- name: Print final report
  ansible.builtin.import_tasks:
    file: verify/report.yml
