---
- name: Read JSON from the Verse customization file
  ansible.builtin.set_fact:
    verse_json_customization: "{{ lookup('ansible.builtin.file', domino__custom_verse_json_file) }}"
  when:
    - domino__custom_verse_json_file | trim | length > 0

- name: Copy and customize Verse customization file
  become: true
  become_user: notes
  ansible.builtin.template:
    src: applications.json.j2
    dest: '/local/notesdata/applications.json'
    mode: u=rw,g=r,o=r
    owner: notes
    group: notes

- name: Enable Verse customization in notes.ini [VOP_EXTENSIBILITY_DATA_PROVIDER_NAME]
  become: true
  become_user: notes
  ansible.builtin.shell:
    chdir: '/local/notesdata'
    cmd: '/opt/hcl/domino/bin/server -c "set conf VOP_EXTENSIBILITY_DATA_PROVIDER_NAME=localFileProvider" 2>&1 &'
  register: verse_cust1_result
  changed_when:
    - verse_cust1_result.changed
    - verse_cust1_result.rc == 0

- name: Enable Verse customization in notes.ini [VOP_Extensibility_Applications_Json_FilePath]
  become: true
  become_user: notes
  ansible.builtin.shell:
    chdir: '/local/notesdata'
    cmd: '/opt/hcl/domino/bin/server -c "set conf VOP_Extensibility_Applications_Json_FilePath=/local/notesdata/applications.json" 2>&1 &'
  register: verse_cust1_result
  changed_when:
    - verse_cust1_result.changed
    - verse_cust1_result.rc == 0
