---
- name: Download the file with the info about the latest startup script version
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/nashcom/domino-startscript/main/latest.txt
    dest: /tmp/latest.txt
    mode: 'u=rwx,g=rx,o=rx'

- name: Store the URL into a value
  ansible.builtin.command:
    cmd: cat /tmp/latest.txt
  changed_when: false
  register: version_result

- name: Create a directory for unpacking the startup script
  ansible.builtin.file:
    path: '{{ domino__startup_script_directory }}'
    state: directory
    owner: '{{ ansible_effective_user_id }}'
    group: '{{ ansible_effective_group_id }}'
    mode: '0755'

- name: Download and unarchive the startup script
  ansible.builtin.unarchive:
    src: '{{ version_result.stdout }}'
    dest: '{{ domino__startup_script_directory }}'
    remote_src: true
    creates: '{{ domino__startup_script_directory }}/install_script'

- name: Update install_script file to enable domino systemd service on deployment inside a container
  become: true
  ansible.builtin.lineinfile:
    path: '{{ domino__startup_script_directory }}/install_script'
    regexp: 'detect_container_env$'
    line: '# detect_container_env'
    backrefs: true
  when: '"molecule-notest" in ansible_skip_tags'

- name: Install the startup script
  become: true
  ansible.builtin.command:
    chdir: '{{ domino__startup_script_directory }}'
    cmd: ./install_script
    creates: /opt/nashcom/startscript/rc_domino_script
