---
- name: Stop the Domino server
  ansible.builtin.import_tasks: manage/domino_stop.yml

- name: Edit script file for unattended installation
  ansible.builtin.lineinfile:
    path: '{{ domino__if_install }}/linux64/script.dat'
    regexp: 'installation_type ='
    line: 'installation_type = 2'

- name: Install Domino Interim fix
  become: true
  args:
    chdir: '{{ domino__if_install }}/linux64'
  ansible.builtin.shell:
    cmd: './install -script script.dat'
  register: if_install_result
  changed_when:
    - if_install_result.changed
    - if_install_result.rc == 0

- name: Start the Domino server
  ansible.builtin.import_tasks: manage/domino_start.yml
