---
- name: Install Domino Startup script
  ansible.builtin.import_tasks:
    file: install/install_startup_script.yml
  when:
    - domino__install_startup_script
    - not startup_script_is_installed

- name: Install Domino
  ansible.builtin.import_tasks:
    file: install/domino_install.yml
  when:
    - domino__install_domino
    - product_info | json_query("[?name==`domino`].do_installation") | first

- name: Install Domino FixPack
  ansible.builtin.import_tasks:
    file: install/fixpack_install.yml
  when:
    - domino__install_fp
    - product_info | json_query("[?name==`fp`].do_installation") | first

- name: Install Domino Interim fix
  ansible.builtin.import_tasks:
    file: install/interim_fix_install.yml
  when:
    - domino__install_if
    - product_info | json_query("[?name==`if`].do_installation") | first

- name: Install Traveler server
  ansible.builtin.import_tasks:
    file: install/traveler_install.yml
  when:
    - domino__install_traveler
    - product_info | json_query("[?name==`traveler`].do_installation") | first

- name: Install Verse
  ansible.builtin.import_tasks:
    file: install/verse_install.yml
  when:
    - domino__install_verse
    - product_info | json_query("[?name==`verse`].do_installation") | first

- name: Install Domino Leap
  ansible.builtin.import_tasks:
    file: install/leap_install.yml
  when:
    - domino__install_leap
    - product_info | json_query("[?name==`leap`].do_installation") | first

- name: Install Nomad
  ansible.builtin.import_tasks:
    file: install/nomad_install.yml
  when:
    - domino__install_nomad
    - product_info | json_query("[?name==`nomad`].do_installation") | first

# - name: Install Domino REST API
#   ansible.builtin.import_tasks:
#     file: install/drapi_install.yml
#   when:
#     - domino__install_domrestapi
#     - not domrestapi_is_installed

- name: Generate Install Report
  ansible.builtin.import_tasks:
    file: install/report.yml
