---
- name: Set Nomad hostname in notes.ini [NOMAD_WEB_HOST]
  become: true
  become_user: notes
  ansible.builtin.shell:
    chdir: '/local/notesdata'
    cmd: '/opt/hcl/domino/bin/server -c "set conf NOMAD_WEB_HOST={{ domino__domino_hostname }}" 2>&1 &'
  register: nomad_hostname_result
  changed_when:
    - nomad_hostname_result.changed
    - nomad_hostname_result.rc == 0

- name: Stop the Domino server
  ansible.builtin.import_tasks: manage/domino_stop.yml

- name: Copy 'nomad' binary files to Domino bineries directory
  become: true
  ansible.builtin.copy:
    src: '{{ domino__nomad_install }}/{{ nomad_binary }}'
    dest: /opt/hcl/domino/notes/latest/linux
    remote_src: true
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  loop:
    - nomad
    - nwsp-linux
    - nomad-files
    - nomad-server-version.txt
  loop_control:
    loop_var: nomad_binary

- name: Start the Domino server
  ansible.builtin.import_tasks: manage/domino_start.yml
