---
- name: Stop the Domino server
  ansible.builtin.import_tasks: manage/domino_stop.yml

- name: Get list of previous Verse binary files
  ansible.builtin.find:
    paths: /local/notesdata/domino/workspace/applications/eclipse/plugins
    patterns: 'ats-*.jar,core-*.jar,sequoia-osgi-*.jar,servlet-*.jar,servers-lookup-*.jar'
  register: verse_files_result

- name: Store a list of Verse binary files
  ansible.builtin.set_fact:
    verse_files: '{{ verse_files_result.files | json_query("[*].path") }}'

- name: Delete previous Verse binary files
  become: true
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop: '{{ verse_files }}'
  when: verse_files | length > 0

- name: Unzip Verse installation package
  become: true
  ansible.builtin.unarchive:
    src: '{{ domino__verse_install }}/HCL_Verse.zip'
    dest: /local/notesdata/domino/workspace/applications
    remote_src: true
    owner: notes
    group: notes

- name: Start the Domino server
  ansible.builtin.import_tasks: manage/domino_start.yml
