---
- name: Set server OS hostname, if not set in values
  ansible.builtin.set_fact:
    # os__hostname: '{{ os__hostname | default(ansible_host, true) }}'
    os__hostname: '{{ os__hostname | default(inventory_hostname, true) }}'
  when: os__set_hostname or os__set_etc_hosts
