# OS related
domino__setup_firewalld: true

# Domino installers
domino__install_path: /local/install
domino__software_dir: ~/software
domino__download_installers: false
domino__install_products:
  - domino
  - verse
  # - nomad
  - traveler
  # - leap
  # - domrestapi
domino__software_use_local_file: false

# Specify the product version to be installed.
# When commented out or with empty value, the latest version is installed.
# domino__domino_version: 14.0FP2
# domino__verse_version: 3.2.2
# domino__nomad_version: 1.0.12IF1
# domino__traveler_version: 14.0FP1
# domino__leap_version: 1.1.4
# domino__domrestapi_version: 1.1

domino__install_startup_script: true
domino__install_ontime: true

# Domino server setup parameters
domino__server_name: Omega
domino__domino_hostname: omega.example.com
domino__domino_domain: Example
domino__org_name: Example
domino__certifier_password: SecretPassw0rd
domino__admin_first_name: Super
domino__admin_last_name: Admin
domino__admin_password: SecretPassw0rd
domino__use_existing_certifier_id: false
domino__use_existing_server_id: false
domino__use_existing_admin_id: false
domino__register_users: false
domino__mail_template: mail145.ntf
domino__use_custom_login: false
domino__create_microca: false
domino__enable_dkim: false
domino__dkim_selector: ''

# Restarts
domino__restart_after_setup: false
domino__wait_mins_after_restart: 1

# Additional servers
domino__setup_additional_servers: false
domino__additional_servers: []
domino__install_as_additional: false
domino__existing_server_name: ''
domino__existing_server_address: ''

# Custom input files
domino__input_data_location: '{{ playbook_dir }}/../local'
domino__cert_id: '{{ domino__input_data_location }}/{{ domino__domino_domain | lower }}/ids/cert.id'
domino__server_id: '{{ domino__input_data_location }}/{{ domino__domino_domain | lower }}/ids/server-{{ domino__server_name | lower }}.id'
domino__admin_id: '{{ domino__input_data_location }}/{{ domino__domino_domain | lower }}/ids/admin.id'

domino__input_data_users: ''      # default value: users.csv
domino__custom_login_db: ''
domino__custom_login_form: ''

# Reports
domino__save_reports: true
domino__reports_dir: '{{ domino__input_data_location }}/reports/{{ domino__domino_domain | lower }}'

# Domino server integration
domino__sametime_server: ''
domino__connections_server: ''

# Monitoring components
domino__install_monitoring: false

# Other
domino__print_credentials: false
