---
- name: Stop the Domino service
  become: true
  ansible.builtin.service:
    name: domino
    state: stopped

- name: Wait for {{ domino__wait_mins_after_restart }} minute(s) to finish server stop
  ansible.builtin.pause:
    minutes: '{{ domino__wait_mins_after_restart }}'

- name: Wait until the Domino server is fully stopped
  become: true
  ansible.builtin.wait_for:
    path: /local/notesdata/IBM_TECHNICAL_SUPPORT/console.log
    search_regex: 'Server shutdown complete'
    timeout: 120
  register: stop_wait_result
  failed_when:
    - stop_wait_result.changed
    - '"Timeout when waiting" not in stop_wait_result.stdout'
  changed_when:
    - stop_wait_result.changed
    - '"Timeout when waiting" in stop_wait_result.stdout'
