---
- name: Start and enable Domino service
  become: true
  ansible.builtin.service:
    name: domino
    state: started

- name: Wait for {{ domino__wait_mins_after_restart }} minute(s) to finish the start
  ansible.builtin.pause:
    minutes: '{{ domino__wait_mins_after_restart }}'

- name: Wait until Server started is logged in the console.log file
  become: true
  ansible.builtin.wait_for:
    path: /local/notesdata/IBM_TECHNICAL_SUPPORT/console.log
    search_regex: 'Server started on physical node'
    timeout: 120
  register: start_wait_result
  changed_when:
    - '"Timeout when waiting" in start_wait_result'
