---
- name: Get list of inventories
  ansible.builtin.uri:
    url: '{{ semaphore__url }}/project/{{ project_number }}/inventory'
    method: GET
    body_format: json
    headers:
      Content-Type: application/json
      Accept: application/json
      Authorization: 'Bearer {{ semaphore_token }}'
  register: inv_list_result

- name: Get list of inventories with the name "{{ semaphore__inventory }}"
  ansible.builtin.set_fact:
    invs: '{{ inv_list_result.json | selectattr("name", "equalto", semaphore__inventory) }}'

- name: Check if multiple inventories with this name exist
  ansible.builtin.assert:
    that:
      - (invs | length) <= 1
    fail_msg: 'Multiple ({{ invs | length }}) inventories with the name {{ semaphore__inventory }} exist. Keep just one of them and delete the others.'

- name: Get the inventory number (if exists)
  ansible.builtin.set_fact:
    inv_number: '{{ (invs | first)["id"] }}'
  when: (invs | length) == 1

- name: Create a new inventory {{ semaphore__inventory }}
  when: (invs | length) == 0
  block:
    - name: Create a new inventory
      ansible.builtin.uri:
        url: '{{ semaphore__url }}/project/{{ project_number }}/inventory'
        method: POST
        body_format: json
        body: >-
          {
            'name': '{{ semaphore__inventory }}',
            'project_id': {{ project_number | int }},
            'inventory': '{{ semaphore__inventory_file }}',
            'type': 'file',
            'ssh_key_id': {{ key_number | int }}
          }
        status_code: 201
        headers:
          Content-Type: application/json
          Accept: application/json
          Authorization: 'Bearer {{ semaphore_token }}'
        return_content: true
      changed_when: create_inv_result.status == 201
      register: create_inv_result

    - name: Store the newly created inventory number
      ansible.builtin.set_fact:
        inv_number: '{{ create_inv_result.json.id }}'


- name: Print Inventory number
  ansible.builtin.debug:
    msg: 'INVENTORY NUMBER: {{ inv_number }}'
