---
- name: Initialize connection to the Semaphore server
  ansible.builtin.import_tasks:
    file: create/init.yml

- name: Get a project
  ansible.builtin.import_tasks:
    file: delete/get_project.yml

- name: Delete template
  ansible.builtin.import_tasks:
    file: delete/delete_template.yml
